INSERT INTO pizza_orders  ( pizza_id, order_id, pizza_name_id,quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name )VALUES (1, 1, 'hawaiian',1, TO_DATE('01/01/2015','MM/DD/YYYY'), '11:38:36', 13.25, 13.25, 'M', 'Classic', 'Sliced Har', 'The Hawaiian Pizza');

INSERT INTO pizza_orders  ( pizza_id, order_id, pizza_name_id,quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name )VALUES (2, 2, 'classic_dl', 1, TO_DATE('01/01/2015','MM/DD/YYYY'), '11:57:40', 16, 16, 'M', 'Classic', 'Pepperoni', 'The Classic Deluxe Pizza');
INSERT INTO pizza_orders  ( pizza_id, order_id, pizza_name_id,quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name )VALUES(3, 2, 'five_chees', 1, TO_DATE('01/01/2015','MM/DD/YYYY'), '11:57:40', 18.5, 18.5, 'L', 'Veggie', 'Mozzarella', 'The Five Cheese Pizza');
INSERT INTO pizza_orders  ( pizza_id, order_id, pizza_name_id,quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name )VALUES (4, 2, 'ital_supr_', 1, TO_DATE('01/01/2015','MM/DD/YYYY'), '11:57:40', 20.75, 20.75, 'L', 'Supreme', 'Calabrese', 'The Italian Supreme Pizza');
INSERT INTO pizza_orders  ( pizza_id, order_id, pizza_name_id,quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name )VALUES (5, 2, 'mexicana', 1, TO_DATE('01/01/2015','MM/DD/YYYY'), '11:57:40', 16, 16, 'M', 'Veggie', 'Tomatoes', 'The Mexicana Pizza');
INSERT INTO pizza_orders  ( pizza_id, order_id, pizza_name_id,quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name )VALUES (6, 2, 'thai_ckn_l', 1, TO_DATE('01/01/2015','MM/DD/YYYY'), '11:57:40', 20.75, 20.75, 'L', 'Chicken', 'Chicken, F', 'The Thai Chicken Pizza');
INSERT INTO pizza_orders  ( pizza_id, order_id, pizza_name_id,quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name )VALUES (7, 3, 'ital_supr_m', 1, TO_DATE('01/01/2015','MM/DD/YYYY'), '12:12:28', 16.5, 16.5, 'M', 'Supreme', 'Calabrese', 'The Italian Supreme Pizza');
INSERT INTO pizza_orders  ( pizza_id, order_id, pizza_name_id,quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name )VALUES (8, 3, 'prsc_argla_l', 1, TO_DATE('01/01/2015','MM/DD/YYYY'), '12:12:38', 20.75, 20.75, 'L', 'Supreme', 'Prosciuttc', 'The Prosciutto and Arugula Pizza');
INSERT INTO pizza_orders  ( pizza_id, order_id, pizza_name_id,quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name )VALUES(9, 4, 'ital_supr_m', 1, TO_DATE('01/01/2015','MM/DD/YYYY'), '12:16:31', 16.5, 16.5, 'M', 'Supreme', 'Calabrese', 'The Italian Supreme Pizza');
INSERT INTO pizza_orders  ( pizza_id, order_id, pizza_name_id,quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name )VALUES (10, 5, 'ital_supr_m', 1, TO_DATE('01/01/2015','MM/DD/YYYY'), '12:21:30', 16.5, 16.5, 'M', 'Supreme', 'Calabrese', 'The Italian Supreme Pizza');
INSERT INTO pizza_orders  ( pizza_id, order_id, pizza_name_id,quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name )VALUES (11, 6, 'bbq_ckn_s', 1, TO_DATE('01/01/2015','MM/DD/YYYY'), '12:29:36', 12.75, 12.75, 'S', 'Chicken', 'Barbecue', 'The Barbecue Chicken Pizza');
INSERT INTO pizza_orders  ( pizza_id, order_id, pizza_name_id,quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name )VALUES(12, 6, 'the_greek_s', 1, TO_DATE('01/01/2015','MM/DD/YYYY'), '12:29:36', 12, 12, 'S', 'Classic', 'Kalamata', 'The Greek Pizza');
INSERT INTO pizza_orders  ( pizza_id, order_id, pizza_name_id,quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name )VALUES (13, 7, 'spinach_s', 1, TO_DATE('01/01/2015','MM/DD/YYYY'), '12:50:37', 12.5, 12.5, 'S', 'Supreme', 'Spinach, F', 'The Spinach Supreme Pizza');
INSERT INTO pizza_orders  ( pizza_id, order_id, pizza_name_id,quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name )VALUES (14, 8, 'spinach_s', 1, TO_DATE('01/01/2015','MM/DD/YYYY'), '12:51:37', 12.5, 12.5, 'S', 'Supreme', 'Spinach, F', 'The Spinach Supreme Pizza');
INSERT INTO pizza_orders  ( pizza_id, order_id, pizza_name_id,quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name )VALUES(15, 9, 'classic_dl_s', 1, TO_DATE('01/01/2015','MM/DD/YYYY'), '12:52:01', 12, 12, 'S', 'Classic', 'Pepperoni', 'The Classic Deluxe Pizza');

COMMIT;
